blank_issues_enabled: false
contact_links:
  - name: NEJILABS | 根島総合研究機構（Nejima Research Organisation）
    url: https://github.com/nejilabs
    about: Group of research lab institutes focusing on different grounds of developmental knowledge | Create new innovations & studies for Nejima & Co. Development, Ltd.
